# Generated by Django 5.0.4 on 2024-04-11 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_alter_quest_name_alter_waypoint_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='start_waypoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quest_starting_here', to='quests.waypoint'),
        ),
    ]
