# Generated by Django 5.0.4 on 2024-04-22 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
        ('quests', '0006_quest_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests_created', to='account.profile'),
        ),
    ]
