# Generated by Django 5.0.4 on 2024-04-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('quests', '0005_remove_quest_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
