# Generated by Django 5.0.4 on 2024-04-11 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=80)),
                ('rating', models.FloatField(default=0)),
                ('difficulty', models.IntegerField(default=1)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quest_passing_through', to='quests.quest')),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='start_waypoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quest_starting_here', to='quests.waypoint'),
        ),
    ]
