# Generated by Django 5.0.4 on 2024-04-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_alter_quest_pub_date_alter_quest_start_waypoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='creator',
        ),
    ]
